### ISSUE TITLE
V4 Breaks on CLI Args

### ISSUE THREAD

**Issue by dairyisscary** [taskworld/eslint-plugin-local#7]
Since v4 running a command like `yarn run eslint . --fix` will crash with:

```console
Oops! Something went wrong! :(

ESLint: 8.56.0

Error: Failed to load plugin 'local' declared in '.eslintrc.js': Unexpected "--fix" as it was not defined in the default hash.
    at parseArguments (node_modules/@thisismanta/pessimist/parseArguments.js:34:19)
    at Object.<anonymous> (node_modules/eslint-plugin-local/index.js:23:35)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at ConfigArrayFactory._loadPlugin (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3433:42)
    at node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3304:33
```

I'm sure this has something to do with the new `test` subcommand args

**Comment by ThisIsManta** [comment]
Yes, sorry for the trouble.
Spare me a day to make a proper fix.

**Comment by ThisIsManta** [comment]
Hi again!
Can you try upgrading to v4.1.1?

**Comment by dairyisscary** [comment]
works for me. :) wow, so fast, thank you!
